# https://github.com/Mic92/sops-nix
# https://unmovedcentre.com/posts/secrets-management/

# Make a user key
# mkdir -p ~/.config/sops/age
# age-keygen -o ~/.config/sops/age/keys.txt

# Get the host public key, derived from the host SSH key
# nix run nixpkgs#ssh-to-age -- -i /etc/ssh/ssh_host_ed25519_key.pub

keys:
  - &users:
    - &pceiley age1q86vdk8lfmmmqu9r8caj5u5srfhkhwgtsq92ls224t00e8j3ndlsa4crhv
  - &hosts:
    - &taftugs age1mt5felmuhnqtr5ksqsxdlu48eeugt5pnusyt5z6dpmaecvuyfyjsjejayf
    - &superslice age12as5qysvqrt3k5ly5nz4u50xlh533n73pkxs8x47lxjjz4eulcpqqykst5
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *pceiley
      - *taftugs
      - *superslice
